return {
  {
    "ibhagwan/fzf-lua",
    enabled = false,
    event = "VimEnter",
    dependencies = {
      "junegunn/fzf",
      "nvim-tree/nvim-web-devicons",
    },
    config = function()
      require("fzf-lua").setup({
        fzf_colors = true,
        winopts = {
          preview = {
            hidden = "hidden",
          },
        },
        keymap = {
          builtin = {
            true,
            ["<esc>"] = "hide",
          },
        },
      })
    end,
    keys = {
      {
        "<leader>F",
        "<cmd>FzfLua builtin<CR>",
        mode = { "n" },
        silent = true,
        desc = "fzf-lua builtin",
      },
      {
        "<leader>fF",
        "<cmd>FzfLua files<CR>",
        mode = { "n" },
        silent = true,
        desc = "Files (Root)",
      },
      {
        "<leader><leader>",
        "<cmd>FzfLua files<CR>",
        mode = { "n" },
        silent = true,
        desc = "Files (Root)",
      },
      {
        "<leader>ff",
        "<cmd>FzfLua files cwd=%:h:p<CR>",
        mode = { "n" },
        silent = true,
        desc = "Files (cwd)",
      },
      {
        "<leader>fg",
        "<cmd>FzfLua git_files<CR>",
        mode = { "n" },
        silent = true,
        desc = "Git Files (cwd)",
      },
      {
        "<leader>fr",
        "<cmd>FzfLua oldfiles<CR>",
        mode = { "n" },
        silent = true,
        desc = "Recent files",
      },
      {
        "<leader>fR",
        "<cmd>FzfLua oldfiles cwd=%:h:p<CR>",
        mode = { "n" },
        silent = true,
        desc = "Recent files (cwd)",
      },
      {
        "<leader>fb",
        "<cmd>FzfLua buffers <CR>",
        mode = { "n" },
        silent = true,
        desc = "Buffers",
      },
      {
        "<leader>,",
        "<cmd>FzfLua buffers <CR>",
        mode = { "n" },
        silent = true,
        desc = "Switch Buffers",
      },
      {
        "<leader>/",
        "<cmd>FzfLua live_grep_glob <CR>",
        mode = { "n" },
        silent = true,
        desc = "Grep (Root Dir)",
      },
      {
        "<leader>:",
        "<cmd>FzfLua command_history <CR>",
        mode = { "n" },
        silent = true,
        desc = "Command History",
      },
      -- {
      --   "<leader>fc",
      --   "<cmd>FzfLua dap_configurations <CR>",
      --   mode = { "n" },
      --   silent = true,
      --   desc = "dap configurations",
      -- },
      {
        "<leader>gc",
        "<cmd>FzfLua git_commits <CR>",
        mode = { "n" },
        silent = true,
        desc = "Git Commits",
      },
      {
        "<leader>gs",
        "<cmd>FzfLua git_status <CR>",
        mode = { "n" },
        silent = true,
        desc = "Git Status",
      },
      {
        "<leader>sa",
        "<cmd>FzfLua autocmds <CR>",
        mode = { "n" },
        silent = true,
        desc = "Autocommands",
      },
      {
        "<leader>sb",
        "<cmd>FzfLua grep_curbuf <CR>",
        mode = { "n" },
        silent = true,
        desc = "Grep Current Buffer",
      },
      {
        "<leader>sc",
        "<cmd>FzfLua command_history <CR>",
        mode = { "n" },
        silent = true,
        desc = "Command History",
      },
      {
        "<leader>sC",
        "<cmd>FzfLua commands <CR>",
        mode = { "n" },
        silent = true,
        desc = "Commands",
      },
      {
        "<leader>sd",
        "<cmd>FzfLua diagnostics_document <CR>",
        mode = { "n" },
        silent = true,
        desc = "Diagnostics Document",
      },
      {
        "<leader>sD",
        "<cmd>FzfLua diagnostics_workspace <CR>",
        mode = { "n" },
        silent = true,
        desc = "Diagnostics Workspace",
      },
      {
        "<leader>sg",
        "<cmd>FzfLua grep_project multiline=2<CR>",
        mode = { "n" },
        silent = true,
        desc = "Grep Project",
      },
      {
        "<leader>sG",
        "<cmd>FzfLua grep_curbuf multiline=2<CR>",
        mode = { "n" },
        silent = true,
        desc = "Grep Current Buffer",
      },
      {
        "<leader>sh",
        "<cmd>FzfLua helptags <CR>",
        mode = { "n" },
        silent = true,
        desc = "Helptags",
      },
      {
        "<leader>sH",
        "<cmd>FzfLua highlights <CR>",
        mode = { "n" },
        silent = true,
        desc = "Highlights",
      },
      {
        "<leader>sj",
        "<cmd>FzfLua jumps <CR>",
        mode = { "n" },
        silent = true,
        desc = "Jumps",
      },
      {
        "<leader>sk",
        "<cmd>FzfLua keymaps <CR>",
        mode = { "n" },
        silent = true,
        desc = "Keymaps",
      },
      {
        "<leader>sl",
        "<cmd>FzfLua loclist <CR>",
        mode = { "n" },
        silent = true,
        desc = "Loclist",
      },
      {
        "<leader>sM",
        "<cmd>FzfLua manpages <CR>",
        mode = { "n" },
        silent = true,
        desc = "Manpages",
      },
      {
        "<leader>sm",
        "<cmd>FzfLua marks <CR>",
        mode = { "n" },
        silent = true,
        desc = "Marks",
      },
      -- {
      --   "<leader>so",
      --   "<cmd>FzfLua options <CR>",
      --   mode = { "n" },
      --   silent = true,
      --   desc = "Options",
      -- },
      {
        "<leader>sR",
        "<cmd>FzfLua resume <CR>",
        mode = { "n" },
        silent = true,
        desc = "Resume",
      },
      {
        "<leader>sq",
        "<cmd>FzfLua quickfix <CR>",
        mode = { "n" },
        silent = true,
        desc = "Quickfix",
      },
      {
        "<leader>sw",
        "<cmd>FzfLua grep_cword multiline=2<CR>",
        mode = { "n" },
        silent = true,
        desc = "Grep Current Word (project)",
      },
      {
        "<leader>sW",
        "<cmd>FzfLua grep_cWORD multiline=2<CR>",
        mode = { "n" },
        silent = true,
        desc = "Grep Current Word (cwd)",
      },
      {
        "<leader>uC",
        "<cmd>FzfLua colorschemes <cr>",
        mode = { "n" },
        silent = true,
        desc = "Colorschemes",
      },
      {
        "<leader>ss",
        "<cmd>FzfLua lsp_document_symbols multiline=2<cr>",
        mode = { "n" },
        silent = true,
        desc = "LSP Document Symbols",
      },
      {
        "<leader>sS",
        "<cmd>FzfLua lsp_workspace_symbols <cr>",
        mode = { "n" },
        silent = true,
        desc = "LSP Workspace Symbols",
      },
      { "<leader>Pb", "<cmd>FzfLua buffers<CR>", desc = "Find buffers", nowait = true, remap = false },
      { "<leader>Pf", "<cmd>FzfLua files<CR>", desc = "Find files", nowait = true, remap = false },
      { "<leader>Pg", "<cmd>FzfLua live_grep<CR>", desc = "Search string live_grep", nowait = true, remap = false },
      { "<leader>Ps", "<cmd>FzfLua grep_project<CR>", desc = "Search text in project", nowait = true, remap = false },
      {
        "<leader>cS",
        "<cmd>FzfLua lsp_live_workspace_symbols<cr>",
        desc = "Live Workspace Symbols",
        nowait = true,
        remap = false,
      },
      {
        "<leader>cw",
        "<cmd>FzfLua diagnostics_workspace<cr>",
        desc = "Workspace Diagnostics",
        nowait = true,
        remap = false,
      },
      -- { "<leader>e", "<cmd>Neotree toggle float<cr>", desc = "Explorer", nowait = true, remap = false },
      { "<leader>fF", "<cmd>FzfLua oldfiles resume=true<CR>", desc = "Find files", nowait = true, remap = false },
      { "<leader>ff", "<cmd>FzfLua files resume=true<CR>", desc = "Find files", nowait = true, remap = false },
      { "<leader>fg", "<cmd>FzfLua git_files<CR>", desc = "Find Git files", nowait = true, remap = false },
      { "<leader>fr", "<cmd>FzfLua oldfiles resume=true<CR>", desc = "Find files", nowait = true, remap = false },
      { "<leader>gb", "<cmd>FzfLua git_branches<cr>", desc = "Checkout branch", nowait = true, remap = false },
      { "<leader>gc", "<cmd>FzfLua git_commits<cr>", desc = "Checkout commit", nowait = true, remap = false },
      { "<leader>gf", "<cmd>FzfLua git_files<cr>", desc = "Find git files", nowait = true, remap = false },
      { "<leader>go", "<cmd>FzfLua git_status<cr>", desc = "Open changed file", nowait = true, remap = false },
      {
        "<leader>sB",
        "<cmd>lua require('fzf-lua').lines()<CR>",
        desc = "fzf find in open buffer lines",
        nowait = true,
        remap = false,
      },
      { "<leader>sC", "<cmd>FzfLua colorschemes<cr>", desc = "Colorscheme", nowait = true, remap = false },
      { "<leader>sR", "<cmd>FzfLua registers<cr>", desc = "Registers", nowait = true, remap = false },
      {
        "<leader>sS",
        "<cmd>FzfLua lsp_workspace_symbols<cr>",
        desc = "Workspace Symbols",
        nowait = true,
        remap = false,
      },
      {
        "<leader>sb",
        "<cmd>lua require('fzf-lua').blines()<CR>",
        desc = "fzf find in current buffer lines",
        nowait = true,
        remap = false,
      },
      { "<leader>sc", "<cmd>FzfLua commands<cr>", desc = "Commands", nowait = true, remap = false },
      {
        "<leader>sd",
        "<cmd>FzfLua lsp_document_diagnostics<cr>",
        desc = "Docment diagnostics",
        nowait = true,
        remap = false,
      },
      { "<leader>sf", "<cmd>FzfLua grep_curbuf<cr>", desc = "Grep in current buffer", nowait = true, remap = false },
      { "<leader>sg", "<cmd>FzfLua grep_project<cr>", desc = "Grep project", nowait = true, remap = false },
      { "<leader>sh", "<cmd>FzfLua helptags<cr>", desc = "Find Help", nowait = true, remap = false },
      { "<leader>sk", "<cmd>FzfLua keymaps<cr>", desc = "Keymaps", nowait = true, remap = false },
      { "<leader>sl", "<cmd>FzfLua blines<cr>", desc = "current buffer lines", nowait = true, remap = false },
      { "<leader>ss", "<cmd>FzfLua lsp_document_symbols<cr>", desc = "Document Symbols", nowait = true, remap = false },
      { "<leader>st", "<cmd>FzfLua tabs<cr>", desc = "Open tabs", nowait = true, remap = false },
      { "<leader>sx", "<cmd>FzfLua quickfix<cr>", desc = "quickfix list", nowait = true, remap = false },
      { "<leader>sy", "<cmd>FzfLua loclist<cr>", desc = "location list", nowait = true, remap = false },
    },
  },
}
