return {
  {
    "nvim-treesitter/nvim-treesitter",
    event = { "BufReadPre", "BufNewFile" },
    build = ":TSUpdate",
    cmd = { "TSInstall", "TSUpdate", "TSUpdateSync" },
    dependencies = {
      "nvim-treesitter/nvim-treesitter-textobjects",
    },
    opts = {
      autopairs = { enable = true },
      ensure_installed = {
        "bash",
        "bibtex",
        "csv",
        "diff",
        "fish",
        "fortran",
        "html",
        "json",
        "julia",
        "latex",
        "lua",
        "markdown",
        "markdown_inline",
        "html",
        "python",
        "regex",
        "toml",
        "tmux",
        "typst",
        "vim",
        "vimdoc",
        "yaml",
      },
      auto_install = true,
      indent = {
        enable = true,
        disable = { "yaml", "fortran" },
      },
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<CR>",
          node_incremental = "<CR>",
          scope_incremental = "<S-CR>",
          node_decremental = "<BS>",
        },
      },
      textobjects = {
        move = {
          enable = true,
          goto_next_start = {
            ["-f"] = "@function.outer",
            ["-c"] = "@conditional.outer",
            ["-a"] = "@class.outer",
            ["-b"] = "@block.outer",
            ["-l"] = "@loop.outer",
            [">f"] = "@function.outer",
            [">c"] = "@conditional.outer",
            [">a"] = "@class.outer",
            [">b"] = "@block.outer",
            [">l"] = "@loop.outer",
          },
          goto_next_end = {
            ["--f"] = "@function.outer",
            ["--c"] = "@conditional.outer",
            ["--a"] = "@class.outer",
            ["--b"] = "@block.outer",
            ["--l"] = "@loop.outer",
            ["<F"] = "@function.outer",
            ["<C"] = "@conditional.outer",
            ["<A"] = "@class.outer",
            ["<B"] = "@block.outer",
            ["<L"] = "@loop.outer",
          },
          goto_previous_start = {
            ["_f"] = "@function.outer",
            ["_c"] = "@conditional.outer",
            ["_a"] = "@class.outer",
            ["_b"] = "@block.outer",
            ["_l"] = "@loop.outer",
            ["<f"] = "@function.outer",
            ["<c"] = "@conditional.outer",
            ["<a"] = "@class.outer",
            ["<b"] = "@block.outer",
            ["<l"] = "@loop.outer",
          },
          goto_previous_end = {
            ["__f"] = "@function.outer",
            ["__c"] = "@conditional.outer",
            ["__a"] = "@class.outer",
            ["__b"] = "@block.outer",
            ["__l"] = "@loop.outer",
            ["<F"] = "@function.outer",
            ["<C"] = "@conditional.outer",
            ["<A"] = "@class.outer",
            ["<B"] = "@block.outer",
            ["<L"] = "@loop.outer",
          },
        },
        select = {
          enable = true,
          keymaps = {
            ["af"] = "@function.outer",
            ["if"] = "@function.inner",
            ["aa"] = "@class.outer",
            ["ia"] = "@class.inner",
            ["al"] = "@loop.outer",
            ["il"] = "@loop.inner",
            ["ac"] = "@conditional.outer",
            ["ic"] = "@conditional.inner",
            ["ao"] = "@block.outer",
            ["io"] = "@block.inner",
          },
        },
      },
    },
    config = function(_, opts)
      require("nvim-treesitter.install").prefer_git = true
      ---@diagnostic disable-next-line: missing-fields
      require("nvim-treesitter.configs").setup(opts)
    end,
  },

  {
    "aaronik/treewalker.nvim",
    opts = {
      highlight = true,
    },
    keys = {
      {
        "<leader>tj",
        "<cmd>Treewalker Down<CR>",
        mode = { "n" },
        desc = "TreeWalker Down",
      },
      {
        "<leader>tk",
        "<cmd>Treewalker Up<CR>",
        mode = { "n" },
        desc = "TreeWalker Up",
      },
      {
        "<leader>th",
        "<cmd>Treewalker Left<CR>",
        mode = { "n" },
        desc = "TreeWalker Left",
      },
      {
        "<leader>tl",
        "<cmd>Treewalker Right<CR>",
        mode = { "n" },
        desc = "TreeWalker Right",
      },
    },
  },
}
